### ISSUE TITLE
Question: how to disable a platform

### ISSUE THREAD

**Issue by tel** [facebookincubator/reindeer#44]
I'm building an application targeting macos and linux exclusively, however by default reindeer seems to solve Cargo dependencies like `[target."cfg(windows)".dependencies.winapi-util]` in `walkdir`.

These aren't causing a significant issue, but they are a bit of noise given my platform interests.

I believe I was able to fix some of this by explicitly declaring my platforms in reindeer.toml.

```toml
# reindeer.toml

[platform.linux-x86_64]
# typical values...
[platform.linux-arm64]
# ...
[platform.macos-x86_64]
# ...
[platform.macos-arm64]
# ...
```

Nevertheless, it appears that the `winapi-util` dependency is getting pulled.

Is there a way to ensure that `cfg(windows)` will evaluate to false?

**Comment by dtolnay** [comment]
I tried running `reindeer buckify` with this Cargo.toml:

```toml
[package]
name = "repro"
publish = false

[dependencies]
walkdir = "2"
```

and this reindeer.toml:

```toml
[platform.linux-x86_64]
target = "x86_64-unknown-linux-gnu"

[platform.linux-arm64]
target = "aarch64-unknown-linux-gnu"

[platform.macos-x86_64]
target = "x86_64-apple-darwin"

[platform.macos-arm64]
target = "aarch64-apple-darwin"
```

and got this generated BUCK file:

```starlark
# @generated by `reindeer buckify`

load("@prelude//rust:cargo_buildscript.bzl", "buildscript_run")
load("@prelude//rust:cargo_package.bzl", "cargo")

http_archive(
    name = "same-file-1.0.6.crate",
    sha256 = "93fc1dc3aaa9bfed95e02e6eadabb4baf7e3078b0bd1b4d7b6b0b68378900502",
    strip_prefix = "same-file-1.0.6",
    urls = ["https://static.crates.io/crates/same-file/1.0.6/download"],
    visibility = [],
)

cargo.rust_library(
    name = "same-file-1.0.6",
    srcs = [":same-file-1.0.6.crate"],
    crate = "same_file",
    crate_root = "same-file-1.0.6.crate/src/lib.rs",
    edition = "2018",
    visibility = [],
)

alias(
    name = "walkdir",
    actual = ":walkdir-2.5.0",
    visibility = ["PUBLIC"],
)

http_archive(
    name = "walkdir-2.5.0.crate",
    sha256 = "29790946404f91d9c5d06f9874efddea1dc06c5efe94541a7d6863108e3a5e4b",
    strip_prefix = "walkdir-2.5.0",
    urls = ["https://static.crates.io/crates/walkdir/2.5.0/download"],
    visibility = [],
)

cargo.rust_library(
    name = "walkdir-2.5.0",
    srcs = [":walkdir-2.5.0.crate"],
    crate = "walkdir",
    crate_root = "walkdir-2.5.0.crate/src/lib.rs",
    edition = "2018",
    visibility = [],
    deps = [":same-file-1.0.6"],
)
```

so I think this has been fixed.
