### ISSUE TITLE
Version-specific fixups

### ISSUE THREAD

**Issue by Ralith** [facebookincubator/reindeer#64]
e.g. [windows_x86_64_msvc](https://github.com/facebook/buck2/blob/f430df86637a8784b1f9d919dc676f64041b3a96/shim/third-party/rust/fixups/windows_x86_64_msvc/fixups.toml#L15)
links a different library with every version, and it's very common to end up with two different versions of it in your build since they release breaking updates regularly.

**Comment by dtolnay** [comment]
Platform fixups have an optional version constraint, so you can already use `platform_fixup` as a version-specific fixup by putting a cfg that is not actually platform sensitive. Something like:

```toml
[platform_fixup.'cfg(all())']
version = "<0.4"
#...

[platform_fixup.'cfg(all(all()))']
version = ">=0.4, <0.6"
#...

[platform_fixup.'cfg(all(all(), all()))']
version = "=0.6"
#...

[platform_fixup.'cfg(all(all(), all(), all()))']
version = ">=0.7"
#...
```
