### ISSUE TITLE
Feature resolution with proc_macros is too broad

### ISSUE THREAD

**Issue by benbrittain** [facebookincubator/reindeer#77]
I was attempting a `#[no_std]` build which ran into an interesting problem, `reindeer` generates the targets with feature resolution across target and host platforms for proc_macros.

This can be reproduced with:
```
pest = {version = "2.8.0", default-features = false }
pest_derive = {version = "2.8.0"}
```

`pest_derive` seemingly winds up enabling "default" in the `pest` crate through a long  `pest_generator -> pest_meta -> pest` dependency chain. However, those features are only ever used behind the proc_macro. Cargo seemingly handle this case, and compiles pest twice, once with all the features, once without. With Buck/Reindeer it now fails, because the features are also enabled in a no_std env.

**Comment by dtolnay** [comment]
There is one feature resolution per universe. Dependencies that are never used from your no-std target platform should be in a different universe. Something like:

```toml
# reindeer.toml

[universe.target]
constraint = "DEFAULT"

[universe.host]
constraint = "//constraints:exec"
include_crates = [
    "pest_derive",
]
```

```toml
# Cargo.toml

[dependencies]
pest = { version = "2.8.0", default-features = false }
pest_derive = { version = "2.8.0", optional = true }
```

This would generate a target like this for pest:

```starlark
rust_library(
    name = "pest-2.8.0",
    ...
    features = select({
        "//constraints:exec": [
            "default",
            "memchr",
            "std",
        ],
        "DEFAULT": [],
    }),
)
```
